package com.helijia.monitor.dal.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.helijia.monitor.dal.model.Student;
import com.helijia.monitor.dal.model.StudentExample;

import tk.mybatis.mapper.common.Mapper;

public interface StudentMapper extends Mapper<Student> {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table student
     *
     * @mbggenerated Mon Aug 10 17:38:47 CST 2015
     */
    int countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table student
     *
     * @mbggenerated Mon Aug 10 17:38:47 CST 2015
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table student
     *
     * @mbggenerated Mon Aug 10 17:38:47 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByPrimaryKey1(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table student
     *
     * @mbggenerated Mon Aug 10 17:38:47 CST 2015
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table student
     *
     * @mbggenerated Mon Aug 10 17:38:47 CST 2015
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table student
     *
     * @mbggenerated Mon Aug 10 17:38:47 CST 2015
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table student
     *
     * @mbggenerated Mon Aug 10 17:38:47 CST 2015
     */
    Student selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table student
     *
     * @mbggenerated Mon Aug 10 17:38:47 CST 2015
     */
    int updateByExampleSelective(@Param("record") Student record,
                                 @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table student
     *
     * @mbggenerated Mon Aug 10 17:38:47 CST 2015
     */
    int updateByExample(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table student
     *
     * @mbggenerated Mon Aug 10 17:38:47 CST 2015
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table student
     *
     * @mbggenerated Mon Aug 10 17:38:47 CST 2015
     */
    int updateByPrimaryKey(Student record);
}
